#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

banner "Релиз MT Cost в Google Play"

# ── 1. Курс золота (спека: человек сверяет витрину перед релизом) ─────────
stage "Курс золота"
say "Перед релизом сверяем крупнейший официальный пакет без скидок и комплектов."
say "Снимок в спеке: 50 000 золота за 7800 ₽ (0,156 ₽/золото), 2026-08-30."
open_url "https://lesta.ru/shop/mt/gold/"
step "Войдите в магазин Lesta, если цены спрятаны за логином."
step "Найдите самый большой пакет золота без скидки и без комплекта."
if confirm "Это по-прежнему 50 000 золота за 7800 ₽?"; then
  write_env GOLD_PACK_GOLD "50000"
  write_env GOLD_PACK_RUBLES "7800"
else
  warn "Снимок курса устарел. Код оценки пока не менялся."
  ask GOLD_PACK_GOLD "Сколько золота в крупнейшем пакете:"
  ask GOLD_PACK_RUBLES "Цена этого пакета в рублях:"
  write_env GOLD_PACK_GOLD "$GOLD_PACK_GOLD"
  write_env GOLD_PACK_RUBLES "$GOLD_PACK_RUBLES"
  warn "Обновите CONTEXT.md и src/packages/player-session/lib/valuation.ts, затем пересоберите AAB."
fi
pause "Enter — дальше."

# ── 2. Аккаунт разработчика ───────────────────────────────────────────────
stage "Аккаунт Google Play Console"
say "Нужен аккаунт разработчика. Разово 25 USD. Должно быть 18+."
open_url "https://play.google.com/console/signup"
step "Если аккаунта ещё нет: примите соглашение, оплатите 25 USD, выберите Personal или Organization, пройдите верификацию."
step "Если аккаунт уже есть — просто закройте вкладку и продолжите."
note "Личный аккаунт после 13.11.2023: до production нужно закрытое тестирование с 12 тестерами 14 дней."
pause "Enter, когда Console открывается под вашим аккаунтом."

# ── 3. Создать приложение ─────────────────────────────────────────────────
stage "Создать приложение"
say "EAS не создаёт карточку в Play. Package уже задан: by.bnd.mtcost"
open_url "https://play.google.com/console/u/0/developers"
step "All apps → Create app."
step "App name: Оценка аккаунта Мира танков"
step "Default language: Русский."
step "App or game: App. Free or paid: Free."
step "Отметьте декларации политик и нажмите Create app."
pause "Enter, когда открыт Dashboard нового приложения."

# ── 4. Service account + JSON ─────────────────────────────────────────────
stage "Google Cloud: service account"
say "EAS Submit ходит в Play Android Developer API от имени service account."
open_url "https://console.cloud.google.com/projectcreate"
step "Создайте проект (или выберите уже существующий) и дождитесь, пока он станет активным."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
step "IAM & Admin → Service Accounts → Create Service Account."
step "Name: mt-cost-play. Description: Play Console uploads for MT Cost."
step "Create and continue, роли не назначайте, Create and close."
step "Скопируйте email вида mt-cost-play@….iam.gserviceaccount.com"
ask GOOGLE_SERVICE_ACCOUNT_EMAIL "Вставьте email service account:"
write_env GOOGLE_SERVICE_ACCOUNT_EMAIL "$GOOGLE_SERVICE_ACCOUNT_EMAIL"
step "У этой учётки: ⋮ → Manage keys → Add key → Create new key → JSON → Create."
step "Файл скачается на компьютер. Его нельзя коммитить."
ask GOOGLE_SERVICE_ACCOUNT_JSON_SRC "Полный путь к скачанному JSON:"
if [[ -f "$GOOGLE_SERVICE_ACCOUNT_JSON_SRC" ]]; then
  cp "$GOOGLE_SERVICE_ACCOUNT_JSON_SRC" google-service-account.json
  write_env GOOGLE_SERVICE_ACCOUNT_KEY_PATH "./google-service-account.json"
  note "скопировали в ./google-service-account.json (уже в .gitignore)"
else
  warn "файл не найден; положите JSON в ./google-service-account.json сами"
  SKIPPED+=("google-service-account.json")
fi

# ── 5. API + приглашение в Play ───────────────────────────────────────────
stage "Права в Play Console"
say "API должен быть включён, а service account приглашён в Console."
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com"
step "Откройте Google Play Android Developer API и нажмите Enable."
open_url "https://play.google.com/console/users-and-permissions"
step "Users and permissions → Invite new users."
step "Email: тот, что только что сохранили в GOOGLE_SERVICE_ACCOUNT_EMAIL"
step "App permissions: выберите MT Cost / эту карточку приложения."
step "Поставьте: View app information (read-only); Edit and delete draft apps;"
step "Release to production, exclude devices, and use Play App Signing;"
step "Release apps to testing tracks; Manage testing tracks and edit tester lists;"
step "Manage store presence."
step "Invite user. Admin / финансы / ответы на отзывы не нужны."
pause "Enter, когда приглашение принято."

# ── 6. Листинг ────────────────────────────────────────────────────────────
stage "Страница магазина"
say "Тексты и файлы уже лежат в store/google-play/."
note "Политика: https://bndby.github.io/mt-cost/privacy/ — живая только после пуша в master."
open_url "https://play.google.com/console/u/0/developers"
step "Приложение → Рост → Присутствие в магазине → Основная страница магазина."
step "Скопируйте название, короткое и полное описание из store/google-play/listing.md"
step "Иконка 512×512: store/google-play/icon-512.png"
step "Графический файл 1024×500: store/google-play/feature-graphic.png"
step "Скриншоты телефона (минимум 2): store/google-play/screenshots/*.png"
step "Категория: Инструменты. Контактный email: expo@bnd.by"
step "Политика конфиденциальности: https://bndby.github.io/mt-cost/privacy/"
pause "Enter, когда листинг сохранён."

# ── 7. Декларации ─────────────────────────────────────────────────────────
stage "Политика приложения"
say "Готовые ответы: store/google-play/app-content.md и data-safety.md"
step "Политика приложения → пройдите все пункты Dashboard «Set up your app»."
step "Реклама: нет."
step "Целевая аудитория: 16+, не для детей."
step "Новости / COVID / госприложения / финансы: нет."
step "Безопасность данных: передаём Lesta идентификатор аккаунта и токен; сами не собираем."
step "Рейтинг контента: анкета утилиты, без насилия и покупок; обмен данными с Lesta — да."
step "Доступ к приложению: да. Вставьте логин и пароль ТЕСТОВОГО аккаунта Lesta"
step "только в форму Play (не в .env и не в чат). Инструкция рецензенту:"
step "нажать «Войти через Lesta», ввести данные на странице Lesta, дождаться возврата."
pause "Enter, когда декларации заполнены."

# ── 8. Тестеры ────────────────────────────────────────────────────────────
stage "Закрытое тестирование"
say "Первый AAB EAS кладёт на internal (черновик). Production — после 12 тестеров × 14 дней,"
say "если аккаунт личный и создан после 13.11.2023. Organization и старые аккаунты — исключение."
open_url "https://play.google.com/console/u/0/developers"
step "Test and release → Testing → Internal testing: после eas submit опубликуйте черновик."
step "Closed testing (не Internal): создайте список email, минимум 12 человек с запасом."
step "Тестеры должны перейти по ссылке opt-in с Android-устройства и оставаться 14 дней."
step "Когда порог выполнен: Dashboard → Apply for production."
pause "Enter, когда список тестеров заведён (или аккаунт не требует закрытого теста)."

note "Дальше в репозитории: npm run build:android && npm run submit:android"
note "submit.production: track=internal, releaseStatus=draft, не отправляет на ревью."

finish
